apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-personal
  description: My personal Backstage instance running in GitHub Codespaces with GitHub OAuth
  annotations:
    github.com/project-slug: yogesh.varadharajan@aspiresys.com/backstage
spec:
  type: website
  lifecycle: experimental
  owner: user:yogesh.varadharajan@aspiresys.com
